### ISSUE TITLE
tailwindui css프레임워크 -package.json 추가

### ISSUE THREAD

**Issue by NSunR** [hanghae99-final-project4/team4-final-project#5]
package.json 추가 바랍니다!
- 수정 내용
- 추가 파일

<tailwindui - css프레임워크 추가>
- 1. 수정 내용 위치 : src/index.css
- 1. 수정 내용: 
ㅇ원래 index.css의 내용 지운 후
아래 코드로 채워주세요.
<해당 내용 코드: 아래 코드 부분 복사해서 붙여넣기 해 주세요.>
`
@tailwind base;
@tailwind components;
@tailwind utilities; 
`

=> 코드 수정 후 결과
![image](https://user-images.githubusercontent.com/76435572/200484604-44c683f7-8d57-43a6-b5cd-64704d470fe6.png)

---

- 2. 수정 내용 위치: TEAM4-FINAL-PROJECT/package.json
- 2. 수정 내용 : 
ㅇ development 내용 아래
devDependencies 내용을 추가.
<해당 내용 코드: 아래 devDependencies 코드 부분 복사해서 붙여넣기 해 주세요.>

`
   "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.18",
    "tailwindcss": "^3.2.1"
  }
`

코드 추가 뒤 결과
=>
![image](https://user-images.githubusercontent.com/76435572/200493695-170beb5a-d27e-49ca-b0a1-82db0b7de7fb.png)

---

- 3. 추가 파일 생성 위치 : TEAM4-FINAL-PROJECT/postcss.config.js
- 3. 추가 파일 내용 :
<해당 내용 코드: 아래 module.exports 코드 부분 복사해서 붙여넣기 해 주세요.>
`
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`

**Comment by NSunR** [comment]
확인하고 추가하시면 댓글달아주세요!

**Comment by shlee1027** [comment]
완료했습니다.
