### ISSUE TITLE
package.json - 로그인, 회원가입에 필요한 라이브러리 추가 확인하고 수정부탁드립니다.

### ISSUE THREAD

**Issue by NSunR** [hanghae99-final-project4/team4-final-project#6]
1. 추가한 라이브러리 :  jwt-decode, react-cookie, axios

2. 수정 위치 : TEAM4-FINAL-PROJECT/package.json

- 2. 수정 내용 :
<해당 내용 코드 : 복사해서 붙여넣기 해주셔도 됩니다.>

`
"dependencies": {
    "@reduxjs/toolkit": "^1.9.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "axios": "^1.1.3",
    "jwt-decode": "^3.1.2",
    "react": "^18.2.0",
    "react-cookie": "^4.1.1",
    "react-dom": "^18.2.0",
    "react-redux": "^8.0.5",
    "react-router-dom": "^6.4.3",
    "react-scripts": "5.0.1",
    "redux": "^4.2.0",
    "socket.io-client": "^4.5.3",
    "styled-components": "^5.3.6",
    "web-vitals": "^2.1.0"
  },
`

- 수정 후 결과
![image](https://user-images.githubusercontent.com/76435572/200497427-2bf53dd3-67b6-479e-b83a-c9d6ef58a2b5.png)

3. 추가한 라이브러리 설치 명령어
1) jwt-decode:
`
 yarn add jwt-decode
`
---
2) react-cookie
`
yarn add react-cookie
`
---
3) axios
`
yarn add axios
`

**Comment by NSunR** [comment]
확인하고 추가되시면 댓글부탁드립니다~

**Comment by shlee1027** [comment]
확인했고 변경 완료했습니다.
